@startuml auth-signin
!theme blueprint
autonumber
actor "Client" as CLIENT
participant "icc-vc-project-auth" as APIAUTH <<Monolithic API>>
participant "Firebase Auth" as FIREBASEAUTH <<External provider>>
participant "MongoDB" as MONGO <<External provider>>
participant "Redis" as REDIS <<Memory cache>>
CLIENT -> APIAUTH : POST v1/sigin
activate APIAUTH
APIAUTH -> FIREBASEAUTH : POST signin
activate FIREBASEAUTH
note over APIAUTH, FIREBASEAUTH: /v1/accounts:signInWithPassword?key=[API_KEY]
alt success signin 
    FIREBASEAUTH --> APIAUTH: 200 OK
    APIAUTH -> REDIS: save idToken of user
    activate REDIS
    REDIS --> APIAUTH: OK
    deactivate REDIS
    APIAUTH -> MONGO: update signin record client
    activate MONGO
    MONGO --> APIAUTH: client data updated
    deactivate MONGO
    APIAUTH --> CLIENT: return 200
    note left of APIAUTH
        {
            "email": "[user@example.com]",
            "displayName": "",
            "idToken": ""
        }
    end note
else error signup
    FIREBASEAUTH --> APIAUTH: Error
    deactivate FIREBASEAUTH
    APIAUTH --> CLIENT: return status code
    deactivate APIAUTH
    note left of APIAUTH
        EMAIL_NOT_FOUND: 404
        INVALID_PASSWORD: 404
        USER_DISABLED: 403
    end note
end
footer @devicc 2023
header icc-vc-project
title SignIn Sequence
@enduml