@startjson
{
    "_id": "7d8ee526-17a6-4838-9c5c-a1b628e8aab1",
    "name": "Mesa vista hermosa",
    "number": 1,
    "places": 4,
    "available": true,
    "createdAt": "2022-01-01T01:01:01.000Z",
    "updatedAt": "2022-01-01T01:01:01.000Z",
    "disableAt": "2022-01-01T01:01:01.000Z"
}
@endjson
